{% set name = "pixell" %}
{% set version = "0.32.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pixell-{{ version }}.tar.gz
  sha256: 765d6ad7f079ab0f2d35d2dce00268af61c5d6022cc694043b41ac7464d95828


build:
  skip: true  # [py<310 or win]
  entry_points:
    - benchmark-pixell-runner = pixell.scripts.benchmark_pixell_runner:main
    - benchmark-pixell = pixell.scripts.benchmark_pixell:main
  number: 0


requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - meson-python                        # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - automake
    - autoconf
    - m4
    - libtool
    - make
  host:
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - libopenblas * *openmp*
    - libblas * *openblas
    - python
    - meson-python
    - python-build
    - cython
    - numpy
    - quaternion
    - scipy
    - astropy-base
    - healpy
    - matplotlib-base
    - pyyaml
    - h5py
    - pillow
    - pyfftw
    - libxcrypt1  # [linux]
    - pip
    - wheel
    - setuptools
  run:
    - llvm-openmp  # [osx]
    - libopenblas * *openmp*
    - libblas * *openblas
    - scipy
    - matplotlib-base
    - python
    - pip
    - coveralls
    - cython
    - ducc0
    - numba
    - pytest
    - pytest-cov
    - astropy-base
    - healpy
    - pyyaml
    - h5py
    - pillow !=10.4.0,>=5.3.0
    - pyfftw
    - setuptools
    - wheel
    - ephem
    - quaternion


test:
  commands:
    - pip check
    - benchmark-pixell-runner --help
    - benchmark-pixell --help
  requires:
    - pip
  imports:
    - pixell

about:
  home: https://github.com/simonsobs/pixell/tree/master
  summary: A rectangular pixel map manipulation and harmonic analysis library derived from Sigurd Naess' enlib.
  description: |
    pixell is a library for loading, manipulating and analyzing maps stored in 
    rectangular pixelization. It is mainly targeted for use with maps of the 
    sky (e.g. CMB intensity and polarization maps, stacks of 21 cm intensity 
    maps, binned galaxy positions or shear) in cylindrical projection, but 
    its core functionality is more general. It extends numpy's ndarray to an 
    ndmap class that associates a World Coordinate System (WCS) with a numpy 
    array. It includes tools for Fourier transforms (through numpy or pyfft) 
    and spherical harmonic transforms (through ducc0) of such maps and tools 
    for visualization (through the Python Image Library).
  license: BSD-3-Clause
  license_file: LICENSE


extra:
  recipe-maintainers:
    - JBorrow
    - msyriac
    - iparask
